version: '3'

services:
    web:
        build: .
        ports:
            - 8080:8080
        volumes:
            - "./:/code"
        environment:
            - PYTHONUNBUFFERED=1
        command: flask run --host 0.0.0.0 --port 5000
