version: '3'

services:
    web:
        build: .
        ports:
            - 8080:8080
        volumes:
            - "./:/code"
        environment:
            - PYTHONUNBUFFERED=1
        command: panel serve /LangChain_QA_Panel_App.py --address 0.0.0.0 --port 8080 --allow-websocket-origin *
